# https://github.com/reactive-tech/kubegres/issues/44

apiVersion: v1
kind: Service
metadata:
  name: mypostgres-primary-np
  namespace: default
  labels:
    app: mypostgres
    replicationRole: primary
  ownerReferences:
  - apiVersion: kubegres.reactive-tech.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: Kubegres
    name: mypostgres
    uid: THIS-WILL-BE-THE-UID-FROM-PRIMARY-SERVICE-CREATED  # change it
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 30500
  selector:
    app: mypostgres
    replicationRole: primary
  sessionAffinity: None
